name: Image Builder

on:
  pull_request:
    types: [opened, reopened]
    paths:
    - '.github/workflows/image-builder.yml'
    - 'image-builder/**'
  push:
    branches:
    - release
    paths:
    - '.github/workflows/image-builder.yml'
    - 'image-builder/**'
  workflow_dispatch:
  workflow_run:
    workflows: [Auto Update Variables]
    types: [completed]

env:
  REGISTRY_IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/image-builder

jobs:
  on-success:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targets:
          - aws-lc
          - modern-toolbox-fedora
    steps:
      - run: echo 'The triggering workflow passed'
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push images
        id: build
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:image-builder"
          file: "./${{ matrix.targets }}.Dockerfile"
          tags: ${{ env.REGISTRY_IMAGE }}:${{ matrix.targets }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
